spring:
  mail:
    default-encoding: UTF-8
    host: smtp.mail.ru
    port: 465
    username:  # логин от учётки Yandex
    password: # специальный пароль для приложения
    test-connection: true # проверка подключения при старте приложения
    protocol: smtps
