#server: # потр развертывания приложения для работы в Idie
  #port: 7000 # потр развертывания приложения для работы в Idie
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://usersDB:5432/usersDB # для доступа к БД в рамках docker
    #url: jdbc:postgresql://localhost:1111/usersDB  # для работы с БД через приложение
    username: user
    password: root
    #url: jdbc:postgresql://localhost:5432/orders  # для работы с БД через приложение
    #username: postgres
    #password: postgres
  data:
    redis:
      url: http://localhost:8080/api/v1/users/verification
jwt:
  secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
  issuer: Fitness_Studio_BUL